# Generated by Django 5.0.1 on 2024-01-31 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_delete_login'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User',
        ),
    ]
